### PR TITLE
Fix MinimumT everywhere

### LINKED ISSUE #43: Wrong threshold in DKG protocol
In https://github.com/drand/kyber/blob/master/share/dkg/dkg.go#L1095, the threshold should be `n/2 + 1` instead of `(n+1)/2`. This bug likely comes from the DEDIS original VSS implementation (see https://github.com/dedis/kyber/issues/374). If the bug is confirmed, I'm happy to submit a PR.

### PR DESCRIPTION
**Pull request by AnomalRoil**
This closes #43 that was actually already fixed in #45, but this also fixes the issue from https://github.com/dedis/kyber/issues/374 where 43 stemmed from.

I'm also adding a few tests just to make sure.

### CODE REVIEW

File: share/dkg/dkg_test.go [hunk 1]
```diff
@@ -1086,3 +1086,28 @@ func TestConfigDuplicate(t *testing.T) {
 	}
 	require.Error(t, c.CheckForDuplicates())
 }
+
+func TestMinimumT(t *testing.T) {
```
Comment (CluEleSsUK) [inline share/dkg/dkg_test.go:1090]: finally you've taken the table-driven test pill, nice ;p
